<?php
/*
	GetGitHubOrganizationRepositoriesAsTableRSS.php
	Title: EFDC GetGitHubOrganizationRepositoriesAsTableRSS Web Service
	Summary: Gets a list of public GitHub repos belonging to the specified organization and returns it in RSS format,
	         with a single entry containing all repos inside an HTML table.
			 This service is meant to use within RSS widgets, such as those in TDX.
             For a more generalized version, see GetGitHubOrganizationRepositoriesRSS.php.
	Author(s): Gabriel Mongefranco <mongefrg@umich.edu>
	Created Date: 4/17/2024
	Last Modified Date: 4/17/2024
	
	Return values:
		Channel/Category - SUCCESS if successful, or ERROR otherwise
		Channel/Comments - error message, if any
		Item/Title - organization name (sanitized)
		Item/Description - HTML table containing all repositories, with title and description (sanitized), 3 columns per row.
		Item/Category - SUCCESS if successful, or ERROR otherwise
		Item/Comments - error message, if any
		
	Remarks:
		Only public repos can be retrieved without an API key.
		
		
*/

// Turn off error reporting (only use in Development environment)
error_reporting(0);
ini_set('display_errors',0);
?>
<?php
header( "Content-type: text/xml");
echo '<?xml version="1.0" encoding="UTF-8" ?>';
?>
 
<?php
// Runtime config
set_time_limit(10);

// Configuration variables
$orgUrl = 'https://github.com/[ORG_NAME]';
$orgDataUrl = 'https://github.com/orgs/[ORG_NAME]/repositories?format=json';

// Return values
$githubRepos = null;
$errorMessage = "";
$orgName = ""; // from input params
$orgNameHTMLSanitized = ""; // sanitized for displaying in RSS feed


// Get query string parameters and Sanitize them
if (isset($_GET['orgName'])) {
	$orgName = $_GET['orgName']; // Get alue from URL parameter
	$orgNameHTMLSanitized = htmlentities($orgName, ENT_QUOTES | ENT_QUOTES,ENT_XHTML); // Sanitize for displaying in RSS feed
}


if($orgName != '') {
	// Build GitHub URL for organization
	$orgUrl = str_replace('[ORG_NAME]', $orgName, $orgUrl);
	// Build GitHub API URL for organization
	$orgDataUrl = str_replace('[ORG_NAME]', $orgName, $orgDataUrl); // Build GitHub URL for
} else {
	$errorMessage .= "Organization name was not provided. Please provide a valid GitHub Organization name without spaces, e.g.:  DepressionCenter \n";
	$orgUrl = "";
	$orgDataUrl = "";
}


try {
  if($orgName != '' and $orgDataUrl != '' and $errorMessage == "") {
		// Query GitHub site
		$contents = file_get_contents($orgDataUrl);
		
		if($contents != '' and $contents != '{"error":"Not Found"}' and str_contains($contents, '{"payload":{')) {
			// Decode JSON data
			$githubRepos = json_decode($contents);
		} else {
			$errorMessage .= "Repository not found.\n";
		}
	}
} catch(Exception $e) {
	$errorMessage .= "Could not connect to or parse data from remote site. \n\n" . $e->getMessage() . "\n";	
}
?>

<rss version="2.0">
<channel>
 <title><?php if($errorMessage=="") { echo trim($orgNameHTMLSanitized . " GitHub Repositories"); } else { echo "EFDC Get GitHub Organization Repositories Web Service"; } ?></title>
 <category><?php if($errorMessage=="") {echo "SUCCESS";} else {echo "ERROR";} ?></category>
 <description><?php if($errorMessage=="") {echo 'List of public GitHub repos from @' . $orgNameHTMLSanitized . ". \n(Generated by EFDC Get GitHub Organization Repositories Web Service - github.com/DepressionCenter).";} else { echo "Gets a list of public GitHub repos belonging to the specified organization and returns it in RSS format. Parameters: ?orgName=DepressionCenter";} ?></description>
 <link><?php echo $orgUrl; ?></link>
 <docs>https://michmed.org/efdc-kb</docs>
 <webMaster>efdc-mobiletech@umich.edu</webMaster>
 <copyright>© 2024 Regents of the University of Michigan</copyright>
 <lastBuildDate><?php echo date('r'); ?></lastBuildDate>
 <pubDate><?php echo date('r'); ?></pubDate>
 <ttl>720</ttl>
 <comments><?php echo htmlentities($errorMessage, ENT_QUOTES | ENT_QUOTES,ENT_XHTML); ?></comments>

<?php
// If connected successfully, extract values, sanitize, and re-format as individual RSS items
if ($orgName!="" and !is_null($githubRepos) and $errorMessage=="") {
	echo "\n<item>\n";
	echo "<title>@" . trim($orgNameHTMLSanitized) . " GitHub Repositories</title>\n";
	echo "<link>" . $orgUrl . "</link>";
	echo "<description>\n<![CDATA[\n";
	echo "<div class=\"table-responsive\">\n";
	echo "\n<br />\n<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"table table-striped table-hover table-bordered table-condensed\" style=\"width: 100%; border-collapse: separate; border-spacing: 0px;\">\n";
	
	$iterationCounter = 0;
	foreach ($githubRepos->payload->repositories as $repo) {
		$iterationCounter += 1;
		if(($iterationCounter % 3 == 1) or ($iterationCounter == 1)) {
			echo "<tr style=\"min-width: 120px; min-height: 40px;\">\n";
		}
		echo "<td style=\"min-width: 30%;\">";
		echo "<h3><strong>";
		echo "<a href=\"" . "https://github.com/" . $orgName . "/" . htmlentities($repo->name, ENT_QUOTES | ENT_QUOTES,ENT_XHTML) . "\">";
		echo htmlentities($repo->name, ENT_QUOTES | ENT_QUOTES,ENT_XHTML);
		echo "</a>";
		echo "</strong></h3>";
		echo "<p>" . htmlentities($repo->description, ENT_QUOTES | ENT_QUOTES,ENT_XHTML) . "</p>";
		echo "</td>\n";
		if($iterationCounter % 3 == 0) {
			echo "</tr>\n";
		}
	}
	if($iterationCounter % 3 != 0) {
			echo "</tr>\n";
		}
	echo "</table>\n</div>\n";
	echo "\n]]>\n</description>\n";
	echo "<comments>" . htmlentities($errorMessage, ENT_QUOTES | ENT_QUOTES,ENT_XHTML) . "</comments>";
	if($errorMessage=='') { echo "<category>SUCCESS</category>"; } else { echo "<category>ERROR</category>\n"; }
	echo "</item>\n";
}
?>
</channel>
</rss>